INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5, image_url, athlete_image_url, athlete_name) VALUES ('Football', 'The world''s most popular sport played in over 200 countries.', 'Brazil has won the FIFA World Cup a record 5 times.', '⚽', 'football', 'The first official football match was played in 1872 between Scotland and England.', 'FIFA was founded in Paris in 1904 and now has 211 member associations.', 'Khvicha Kvaratskhelia, known as Kvaradona, starred for Napoli and PSG and is Georgia''s biggest football star.', 'Giorgi Mamardashvili is Georgia''s world class goalkeeper, signed by Liverpool FC.', 'Georgia qualified for their first ever UEFA European Championship in 2024, beating Portugal in the group stage!', 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800', 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400', 'Khvicha Kvaratskhelia');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5, image_url, athlete_image_url, athlete_name) VALUES ('Basketball', 'Born in 1891, now one of the biggest sports on the planet.', 'Georgia has two active NBA players - Sandro Mamukelashvili and Goga Bitadze!', '🏀', 'basketball', 'Basketball was invented in December 1891 by Dr. James Naismith in Massachusetts.', 'Goga Bitadze is a Georgian NBA center who plays for the Orlando Magic, known for his defensive skills.', 'Sandro Mamukelashvili is a Georgian NBA forward who has played for the Milwaukee Bucks and San Antonio Spurs.', 'Tornike Shengelia is one of the greatest Georgian basketball players, dominating EuroLeague with CSKA Moscow and Baskonia.', 'The Boston Celtics have won the most NBA Championships with 17 titles.','/images/basketball.jpg', 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400', 'Goga Bitadze');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5, image_url, athlete_image_url, athlete_name) VALUES ('Formula 1', 'The pinnacle of motorsport combining speed, technology and skill.', 'Michael Schumacher and Lewis Hamilton both won 7 World Championships.', '🏎️', 'formula1', 'The first Formula 1 race was held in 1950 at Silverstone, England.', 'Michael Schumacher won 7 World Championships, a record later matched by Lewis Hamilton.', 'Ferrari is the oldest and most successful team in Formula 1 history.', 'The Monaco Grand Prix is the most prestigious and glamorous race in Formula 1.', 'F1 cars can reach speeds of over 370 km/h and pull up to 5G of force in corners.', '/images/formula1.jpg', 'https://images.unsplash.com/photo-1541447271487-09612b3f49f7?w=400', 'Lewis Hamilton');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5, image_url, athlete_image_url, athlete_name) VALUES ('Tennis', 'One of the most elegant and demanding sports in the world.', 'Novak Djokovic holds the record for most Grand Slam titles with 24.', '🎾', 'tennis', 'Nikoloz Basilashvili is Georgia''s greatest tennis player, reaching a career high of world No. 16 and winning multiple ATP titles.', 'Basilashvili won the Qatar Open twice and the Munich Open, representing Georgia at the highest level of tennis.', 'Wimbledon is the oldest tennis tournament in the world, first held in 1877.', 'Novak Djokovic has won 24 Grand Slam titles, the most in history.', 'Rafael Nadal won the French Open a record 14 times throughout his legendary career.', 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800', 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=400', 'Nikoloz Basilashvili');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5, image_url, athlete_image_url, athlete_name) VALUES ('NFL', 'American Football is one of the most watched sports in the USA.', 'The Super Bowl is the most watched TV event in American history.', '🏈', 'nfl', 'American Football evolved from rugby in the late 19th century in the USA.', 'The NFL was founded in 1920 and has grown into a multi-billion dollar league.', 'The Super Bowl has been played every year since 1967 and is watched by over 100 million people.', 'Tom Brady won 7 Super Bowl championships, the most by any player in NFL history.', 'The Kansas City Chiefs led by Patrick Mahomes are one of the most dominant recent dynasties.', '/images/nfl.jpg', 'https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=400', 'Tom Brady');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5, image_url, athlete_image_url, athlete_name) VALUES ('MMA & UFC', 'Mixed Martial Arts is the fastest growing sport in the world.', 'Georgia has two current UFC champions - Ilia Topuria and Merab Dvalishvili!', '🥊', 'mma', 'Ilia Topuria became UFC Featherweight Champion in February 2024 by knocking out Alexander Volkanovski in the 2nd round.', 'Merab Dvalishvili became UFC Bantamweight Champion in 2024, making Georgia the only country with two simultaneous UFC champions.', 'Topuria then moved up to Lightweight and knocked out Dustin Poirier to become a two-division UFC champion.', 'Khabib Nurmagomedov retired undefeated with a 29-0 record and is considered one of the greatest UFC fighters ever.', 'Jon Jones is considered by many as the greatest UFC fighter of all time.', '/images/mma.jpg', 'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=400', 'Ilia Topuria');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5, image_url, athlete_image_url, athlete_name) VALUES ('Rugby', 'A full contact team sport played in over 120 countries worldwide.', 'Georgia''s rugby team, the Lelos, is one of the rising powers in world rugby!', '🏉', 'rugby', 'Georgia''s national rugby team is nicknamed the Lelos and has been consistently ranked among the top 12 teams in the world.', 'Georgia qualified for every Rugby World Cup since 2003 and is known for its powerful scrum.', 'The Lelos beat Russia, Tonga, and Uruguay at various World Cups, showing Georgia is a serious rugby nation.', 'Rugby is hugely popular in Georgia and the Lelos are considered national heroes.', 'South Africa has won the Rugby World Cup a record 4 times, with the All Blacks of New Zealand winning 3 times.', '/images/rugby.jpg', 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400', 'Georgia Lelos');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5, image_url, athlete_image_url, athlete_name) VALUES ('Olympics', 'The greatest sporting event on Earth held every 4 years.', 'Georgia has won Olympic medals in wrestling, judo, weightlifting and shooting!', '🏅', 'olympics', 'Georgia first competed as an independent nation at the 1996 Atlanta Olympics and won 2 gold medals immediately.', 'Lasha Talakhadze is Georgia''s greatest Olympian, winning gold in weightlifting at Rio 2016 and Tokyo 2020 while breaking world records.', 'Georgian wrestlers have been among the strongest in the world, winning multiple Olympic medals over the years.', 'Georgia has consistently punched above its weight at the Olympics, winning medals in judo, wrestling and weightlifting.', 'The next Summer Olympics will be held in Los Angeles, USA in 2028 where Georgia will aim for more medals.', '/images/olympics.jpg', 'https://images.unsplash.com/photo-1569517282132-25d22f4573e6?w=400', 'Lasha Talakhadze');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5, image_url, athlete_image_url, athlete_name) VALUES ('World Cup 2026', 'The FIFA World Cup 2026 will be hosted by USA, Canada and Mexico.', 'The 2026 World Cup will be the first ever with 48 teams competing!', '🏆', 'worldcup2026', 'The 2026 World Cup will be hosted across USA, Canada and Mexico making it the largest World Cup ever.', 'For the first time ever 48 national teams will compete, giving smaller nations more chances to qualify.', 'The final will be played at MetLife Stadium in New Jersey, USA in July 2026.', 'This will be the largest World Cup in history with 104 total matches played.', 'Brazil, France and England are among the favorites to win the 2026 World Cup.', '/images/worldcup.jpg', 'https://images.unsplash.com/photo-1551958219-acbc608c6377?w=400', 'Khvicha Kvaratskhelia');

-- FOOTBALL ATHLETES
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Khvicha Kvaratskhelia', 'Football', 'Georgian', 'Known as Kvaradona, Khvicha is Georgia''s greatest ever footballer. He rose to fame at Napoli winning Serie A and moved to PSG in 2025.', 'Serie A Champion 2023, UEFA Euro 2024 participant', true);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Giorgi Mamardashvili', 'Football', 'Georgian', 'World class goalkeeper signed by Liverpool FC. Considered one of the best goalkeepers in Europe after stunning performances at Valencia and Euro 2024.', 'Signed by Liverpool FC, Euro 2024 standout performer', true);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Giorgi Chakvetadze', 'Football', 'Georgian', 'Creative midfielder who plays in Europe and is a key member of the Georgian national team. Known for his technical ability and vision.', 'Key Georgian national team midfielder', true);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Otar Kiteishvili', 'Football', 'Georgian', 'Talented Georgian midfielder playing in the Bundesliga. A crucial part of Georgia''s historic Euro 2024 campaign.', 'Bundesliga player, Euro 2024 hero', true);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Zuriko Davitashvili', 'Football', 'Georgian', 'Fast and tricky winger who plays in Ligue 1. One of Georgia''s most exciting attacking players with pace and skill to beat any defender.', 'Ligue 1 player, Georgian national team star', true);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Lionel Messi', 'Football', 'Argentine', 'Widely considered the greatest footballer of all time. Won 8 Ballon d''Or awards and led Argentina to the 2022 World Cup title.', '8x Ballon d''Or, 2022 World Cup Winner, Copa America 2021', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Cristiano Ronaldo', 'Football', 'Portuguese', 'One of the greatest footballers ever with over 900 career goals. Won 5 Ballon d''Or awards and 5 Champions League titles.', '5x Ballon d''Or, 5x Champions League Winner', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Kylian Mbappé', 'Football', 'French', 'The fastest player in the world and France''s biggest star. Won the World Cup at just 19 years old and joined Real Madrid in 2024.', '2018 World Cup Winner, signed by Real Madrid 2024', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Erling Haaland', 'Football', 'Norwegian', 'The most deadly striker in the world. Scored 36 Premier League goals in his debut season at Manchester City, breaking all records.', 'Premier League record 36 goals in one season', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Jude Bellingham', 'Football', 'English', 'England''s biggest star and one of the best midfielders in the world. Joined Real Madrid in 2023 and won La Liga in his first season.', 'La Liga Winner 2024 with Real Madrid', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Kevin De Bruyne', 'Football', 'Belgian', 'The best playmaker of his generation. Has won 6 Premier League titles with Manchester City and is known for his incredible passing.', '6x Premier League Winner, Champions League 2023', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Vinícius Júnior', 'Football', 'Brazilian', 'One of the most exciting wingers in the world. Won the Ballon d''Or in 2024 and is the heart of Real Madrid''s attack.', 'Ballon d''Or 2024, 2x Champions League Winner', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Rodri', 'Football', 'Spanish', 'The best defensive midfielder in the world. Won the Ballon d''Or in 2023 and led Spain to Euro 2024 glory.', 'Ballon d''Or 2023, Euro 2024 Winner', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Mohamed Salah', 'Football', 'Egyptian', 'Liverpool''s legendary Egyptian King. One of the most prolific scorers in Premier League history with incredible speed and finishing.', '2x Premier League Golden Boot, Champions League Winner 2019', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Harry Kane', 'Football', 'English', 'England''s all time top scorer and one of the best strikers in the world. Joined Bayern Munich in 2023 and broke the Bundesliga scoring record.', 'England all time top scorer, Bundesliga record scorer', false);

-- BASKETBALL ATHLETES
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('LeBron James', 'Basketball', 'American', 'The greatest basketball player of his generation. Won 4 NBA championships with 3 different teams and is the NBA all time leading scorer.', 'NBA All Time Leading Scorer, 4x NBA Champion', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Stephen Curry', 'Basketball', 'American', 'The greatest shooter in NBA history. Revolutionized basketball with his three point shooting and won 4 NBA titles with the Golden State Warriors.', '4x NBA Champion, 2x MVP, Greatest Shooter Ever', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Kevin Durant', 'Basketball', 'American', 'One of the most skilled scorers in NBA history. Won 2 NBA championships and 2 Finals MVP awards with the Golden State Warriors.', '2x NBA Champion, 2x Finals MVP', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Nikola Jokić', 'Basketball', 'Serbian', 'The most dominant center in modern basketball. Won 3 MVP awards and led Denver Nuggets to their first ever NBA Championship in 2023.', '3x MVP, NBA Champion 2023', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Giannis Antetokounmpo', 'Basketball', 'Greek', 'The Greek Freak. Won 2 MVP awards and led the Milwaukee Bucks to the NBA Championship in 2021 with a legendary Finals performance.', '2x MVP, NBA Champion 2021', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Luka Dončić', 'Basketball', 'Slovenian', 'The best young player in the NBA. Led Dallas Mavericks to the NBA Finals in 2024 and is considered the future of basketball.', 'NBA Finals 2024, EuroLeague Champion at 18', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Jayson Tatum', 'Basketball', 'American', 'Boston Celtics superstar who led his team to the NBA Championship in 2024. Known for his clutch scoring and two way play.', 'NBA Champion 2024 with Boston Celtics', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Joel Embiid', 'Basketball', 'Cameroonian', 'One of the most dominant centers in the NBA. Won the MVP award in 2023 and is known for his unstoppable scoring ability.', 'NBA MVP 2023', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Kawhi Leonard', 'Basketball', 'American', 'One of the best two way players in NBA history. Won NBA Championships with two different teams and is known as The Klaw.', '2x NBA Champion, 2x Finals MVP', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Anthony Davis', 'Basketball', 'American', 'One of the most dominant big men in the NBA. Won the NBA Championship with the LA Lakers in 2020 alongside LeBron James.', 'NBA Champion 2020, 8x All Star', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Devin Booker', 'Basketball', 'American', 'Phoenix Suns superstar and one of the best scorers in the NBA. Won Olympic gold with Team USA at the Paris 2024 Olympics.', 'Olympic Gold 2024, NBA All Star', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Shai Gilgeous-Alexander', 'Basketball', 'Canadian', 'Oklahoma City Thunder star and one of the most unstoppable scorers in the NBA. Led OKC to the best record in the league in 2024.', 'NBA scoring leader, All Star', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Jimmy Butler', 'Basketball', 'American', 'One of the most competitive players in the NBA. Led the Miami Heat to two NBA Finals and is known for his incredible clutch performances.', '2x NBA Finals, 6x All Star', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Damian Lillard', 'Basketball', 'American', 'One of the greatest point guards of his generation. Known for his incredible clutch shooting and joined the Milwaukee Bucks in 2023.', '7x All Star, clutch shooting legend', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Ja Morant', 'Basketball', 'American', 'Memphis Grizzlies electrifying point guard. Known for his incredible athleticism and highlight reel dunks. One of the most exciting players in the NBA.', 'NBA Most Improved Player 2022', false);

-- FORMULA 1 ATHLETES
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Max Verstappen', 'Formula 1', 'Dutch', 'The most dominant Formula 1 driver of his era. Won 4 consecutive World Championships with Red Bull Racing from 2021 to 2024.', '4x Formula 1 World Champion', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Lewis Hamilton', 'Formula 1', 'British', 'The most decorated Formula 1 driver in history. Won 7 World Championships tying Michael Schumacher''s record and joined Ferrari in 2025.', '7x Formula 1 World Champion, Joined Ferrari 2025', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Charles Leclerc', 'Formula 1', 'Monegasque', 'Ferrari''s star driver and one of the fastest qualifiers on the grid. Known for his incredible one lap pace and passionate racing style.', 'Multiple F1 race wins with Ferrari', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Lando Norris', 'Formula 1', 'British', 'McLaren''s rising star and one of the most popular drivers on the grid. Won his first Formula 1 race in 2024 and is challenging for the championship.', 'First F1 win 2024, McLaren lead driver', false);

-- TENNIS ATHLETES
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Novak Djokovic', 'Tennis', 'Serbian', 'The greatest tennis player of all time by Grand Slam titles. Won 24 Grand Slams and Olympic gold at Paris 2024 completing his career golden slam.', '24x Grand Slam Winner, Olympic Gold 2024', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Carlos Alcaraz', 'Tennis', 'Spanish', 'The future of tennis and one of the most exciting players ever. Won 4 Grand Slam titles before turning 22 including back to back Wimbledon titles.', '4x Grand Slam Winner, 2x Wimbledon Champion', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Jannik Sinner', 'Tennis', 'Italian', 'World number one and the best player in the world in 2024. Won the Australian Open and US Open in 2024 to establish himself as the top player.', 'World No.1, 2x Grand Slam Winner 2024', false);

-- NFL ATHLETES
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Patrick Mahomes', 'NFL', 'American', 'The best quarterback in the NFL today. Led the Kansas City Chiefs to 3 Super Bowl victories and is considered the heir to Tom Brady''s legacy.', '3x Super Bowl Champion, 2x NFL MVP', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Tom Brady', 'NFL', 'American', 'The greatest NFL player of all time. Won 7 Super Bowl championships with 3 different teams and retired as the greatest quarterback ever.', '7x Super Bowl Champion, Greatest QB Ever', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Josh Allen', 'NFL', 'American', 'Buffalo Bills superstar quarterback and one of the most exciting players in the NFL. Known for his powerful arm and incredible athleticism.', 'NFL MVP candidate, Pro Bowl selection', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Joe Burrow', 'NFL', 'American', 'Cincinnati Bengals franchise quarterback who led his team to the Super Bowl in 2022. Known for his cool demeanor and pinpoint accuracy.', 'Super Bowl LVI appearance, AFC Champion 2022', false);

-- MMA/UFC ATHLETES
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Jon Jones', 'MMA & UFC', 'American', 'Considered the greatest UFC fighter of all time. Won championships in two weight classes and has never lost a fight by decision or finish in his career.', 'UFC Light Heavyweight and Heavyweight Champion', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Khabib Nurmagomedov', 'MMA & UFC', 'Russian', 'Retired undefeated with a 29-0 record. The most dominant UFC Lightweight Champion in history who suffocated every opponent with his wrestling.', 'UFC Lightweight Champion, 29-0 undefeated', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Islam Makhachev', 'MMA & UFC', 'Russian', 'Current UFC Lightweight Champion and pound for pound number one fighter in the world. Trained by Khabib and is considered his successor.', 'UFC Lightweight Champion, P4P #1', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Conor McGregor', 'MMA & UFC', 'Irish', 'The biggest star in MMA history. Won championships in two weight classes simultaneously and brought UFC to a global mainstream audience.', '2x UFC Champion, Biggest MMA star ever', false);

-- RUGBY ATHLETES
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Antoine Dupont', 'Rugby', 'French', 'The best rugby player in the world. Won the Rugby World Player of the Year award and led France to Olympic gold in Rugby Sevens at Paris 2024.', 'World Player of the Year, Olympic Gold 2024', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Siya Kolisi', 'Rugby', 'South African', 'South Africa''s inspirational captain who led the Springboks to back to back Rugby World Cup victories in 2019 and 2023.', '2x Rugby World Cup Winner as Captain', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Richie McCaw', 'Rugby', 'New Zealander', 'The greatest rugby player of all time. Led the All Blacks to back to back Rugby World Cup victories in 2011 and 2015 and won 3 World Player of the Year awards.', '2x Rugby World Cup Winner, 3x World Player of Year', false);

-- OLYMPICS ATHLETES
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Michael Phelps', 'Olympics', 'American', 'The most decorated Olympian of all time with 23 gold medals. Dominated swimming for over a decade and is considered the greatest Olympian ever.', '23 Olympic Gold Medals, 28 total medals', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Larisa Latynina', 'Olympics', 'Soviet', 'The most decorated female Olympian in history until Michael Phelps broke her record. Won 9 gold medals in gymnastics across three Olympic Games.', '9 Olympic Gold Medals in Gymnastics', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Simone Biles', 'Olympics', 'American', 'The greatest gymnast of all time. Won 7 Olympic medals including 4 gold and is the most decorated American gymnast in history.', '7 Olympic Medals, Greatest Gymnast Ever', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Lasha Talakhadze', 'Olympics', 'Georgian', 'Georgia''s greatest ever Olympian. Won back to back Olympic gold medals in weightlifting while breaking world records at both Rio 2016 and Tokyo 2020.', '2x Olympic Gold, Multiple World Records', true);

-- WORLD CUP 2026 TEAMS
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Argentina', 'World Cup 2026', 'Argentine', 'Reigning World Champions led by Lionel Messi. Argentina will look to defend their 2022 title and become the first back to back champions since Brazil in 1958 and 1962.', 'Reigning World Champions 2022', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('France', 'World Cup 2026', 'French', 'One of the favorites with stars like Mbappe, Griezmann and Camavinga. France reached the 2022 World Cup final and will be hungry to go one better in 2026.', '2022 World Cup Runners Up, 1998 Champions', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Brazil', 'World Cup 2026', 'Brazilian', 'The most successful World Cup nation with 5 titles. Brazil will look to end their long wait for a sixth title in 2026 with Vinicius Jr leading the attack.', '5x World Cup Champions', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('England', 'World Cup 2026', 'English', 'England reached the Euro 2024 final and will be among the favorites in 2026. Led by Harry Kane and Jude Bellingham, they are hungry for their second ever World Cup.', 'Euro 2024 Finalists, 1966 World Cup Winners', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Spain', 'World Cup 2026', 'Spanish', 'Euro 2024 Champions and one of the most technically gifted teams in the world. Spain will be strong favorites for the 2026 World Cup.', 'Euro 2024 Champions, 2010 World Cup Winners', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Germany', 'World Cup 2026', 'German', 'Germany will host Euro 2024 and are always dangerous at World Cups. With young talent emerging they could challenge for the 2026 title.', '4x World Cup Winners', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Portugal', 'World Cup 2026', 'Portuguese', 'Led by Cristiano Ronaldo who is desperate to win his first World Cup before retiring. Portugal have exciting young talent alongside their legendary captain.', 'Euro 2016 Champions', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Netherlands', 'World Cup 2026', 'Dutch', 'The Netherlands reached the 2022 World Cup quarterfinals and have exciting talent in Virgil van Dijk and Cody Gakpo. A dangerous dark horse for 2026.', '2022 World Cup Quarterfinalists', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Italy', 'World Cup 2026', 'Italian', 'The 2006 World Cup winners failed to qualify in 2018 and 2022. Italy will be desperate to return to the World Cup stage and prove themselves in 2026.', '4x World Cup Winners, 2020 Euro Champions', false);
INSERT INTO athlete (name, sport, nationality, info, achievement, georgian) VALUES ('Belgium', 'World Cup 2026', 'Belgian', 'Belgium''s golden generation featuring De Bruyne and Lukaku may have one last shot at glory in 2026. Ranked among the top teams in the world for years.', 'FIFA World Ranking Top 5', false);