INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5) VALUES ('Football', 'The world''s most popular sport played in over 200 countries.', 'Brazil has won the FIFA World Cup a record 5 times.', '⚽', 'football', 'The first official football match was played in 1872 between Scotland and England.', 'FIFA was founded in Paris in 1904 and now has 211 member associations.', 'Khvicha Kvaratskhelia, known as Kvaradona, starred for Napoli and PSG and is Georgia''s biggest football star.', 'Giorgi Mamardashvili is Georgia''s world class goalkeeper, signed by Liverpool FC.', 'Georgia qualified for their first ever UEFA European Championship in 2024, beating Portugal in the group stage!');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5) VALUES ('Basketball', 'Born in 1891, now one of the biggest sports on the planet.', 'Georgia has two active NBA players - Sandro Mamukelashvili and Goga Bitadze!', '🏀', 'basketball', 'Basketball was invented in December 1891 by Dr. James Naismith in Massachusetts.', 'Goga Bitadze is a Georgian NBA center who plays for the Orlando Magic, known for his defensive skills.', 'Sandro Mamukelashvili is a Georgian NBA forward who has played for the Milwaukee Bucks and San Antonio Spurs.', 'Tornike Shengelia is one of the greatest Georgian basketball players, dominating EuroLeague with CSKA Moscow and Baskonia.', 'The Boston Celtics have won the most NBA Championships with 17 titles.');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5) VALUES ('Formula 1', 'The pinnacle of motorsport combining speed, technology and skill.', 'Michael Schumacher and Lewis Hamilton both won 7 World Championships.', '🏎️', 'formula1', 'The first Formula 1 race was held in 1950 at Silverstone, England.', 'Michael Schumacher won 7 World Championships, a record later matched by Lewis Hamilton.', 'Ferrari is the oldest and most successful team in Formula 1 history.', 'The Monaco Grand Prix is the most prestigious and glamorous race in Formula 1.', 'F1 cars can reach speeds of over 370 km/h and pull up to 5G of force in corners.');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5) VALUES ('Tennis', 'One of the most elegant and demanding sports in the world.', 'Novak Djokovic holds the record for most Grand Slam titles with 24.', '🎾', 'tennis', 'Nikoloz Basilashvili is Georgia''s greatest tennis player, reaching a career high of world No. 16 and winning multiple ATP titles.', 'Basilashvili won the Qatar Open twice and the Munich Open, representing Georgia at the highest level of tennis.', 'Wimbledon is the oldest tennis tournament in the world, first held in 1877.', 'Novak Djokovic has won 24 Grand Slam titles, the most in history.', 'Rafael Nadal won the French Open a record 14 times throughout his legendary career.');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5) VALUES ('NFL', 'American Football is one of the most watched sports in the USA.', 'The Super Bowl is the most watched TV event in American history.', '🏈', 'nfl', 'American Football evolved from rugby in the late 19th century in the USA.', 'The NFL was founded in 1920 and has grown into a multi-billion dollar league.', 'The Super Bowl has been played every year since 1967 and is watched by over 100 million people.', 'Tom Brady won 7 Super Bowl championships, the most by any player in NFL history.', 'The Kansas City Chiefs led by Patrick Mahomes are one of the most dominant recent dynasties.');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5) VALUES ('MMA & UFC', 'Mixed Martial Arts is the fastest growing sport in the world.', 'Georgia has two current UFC champions - Ilia Topuria and Merab Dvalishvili!', '🥊', 'mma', 'Ilia Topuria became UFC Featherweight Champion in February 2024 by knocking out Alexander Volkanovski in the 2nd round.', 'Merab Dvalishvili became UFC Bantamweight Champion in 2024, making Georgia the only country with two simultaneous UFC champions.', 'Topuria then moved up to Lightweight and knocked out Dustin Poirier to become a two-division UFC champion.', 'Khabib Nurmagomedov retired undefeated with a 29-0 record and is considered one of the greatest UFC fighters ever.', 'Jon Jones is considered by many as the greatest UFC fighter of all time.');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5) VALUES ('Rugby', 'A full contact team sport played in over 120 countries worldwide.', 'Georgia''s rugby team, the Lelos, is one of the rising powers in world rugby!', '🏉', 'rugby', 'Georgia''s national rugby team is nicknamed the Lelos and has been consistently ranked among the top 12 teams in the world.', 'Georgia qualified for every Rugby World Cup since 2003 and is known for its powerful scrum.', 'The Lelos beat Russia, Tonga, and Uruguay at various World Cups, showing Georgia is a serious rugby nation.', 'Rugby is hugely popular in Georgia and the Lelos are considered national heroes.', 'South Africa has won the Rugby World Cup a record 4 times, with the All Blacks of New Zealand winning 3 times.');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5) VALUES ('Olympics', 'The greatest sporting event on Earth held every 4 years.', 'Georgia has won Olympic medals in wrestling, judo, weightlifting and shooting!', '🏅', 'olympics', 'Georgia first competed as an independent nation at the 1996 Atlanta Olympics and won 2 gold medals immediately.', 'Lasha Talakhadze is Georgia''s greatest Olympian, winning gold in weightlifting at Rio 2016 and Tokyo 2020 while breaking world records.', 'Georgian wrestlers have been among the strongest in the world, winning multiple Olympic medals over the years.', 'Georgia has consistently punched above its weight at the Olympics, winning medals in judo, wrestling and weightlifting.', 'The next Summer Olympics will be held in Los Angeles, USA in 2028 where Georgia will aim for more medals.');

INSERT INTO sport (name, description, fact, emoji, url_name, fact1, fact2, fact3, fact4, fact5) VALUES ('World Cup 2026', 'The FIFA World Cup 2026 will be hosted by USA, Canada and Mexico.', 'The 2026 World Cup will be the first ever with 48 teams competing!', '🏆', 'worldcup2026', 'The 2026 World Cup will be hosted across USA, Canada and Mexico making it the largest World Cup ever.', 'For the first time ever 48 national teams will compete, giving smaller nations more chances to qualify.', 'The final will be played at MetLife Stadium in New Jersey, USA in July 2026.', 'This will be the largest World Cup in history with 104 total matches played.', 'Brazil, France and England are among the favorites to win the 2026 World Cup.');